<?php

namespace V1nk0\LaravelPostat\Enums;

enum ReasonCode: string
{
    case AA = 'AA';
    case AAO = 'AAO';
    case AAQ = 'AAQ';
    case AB = 'AB';
    case AC = 'AC';
    case ADC = 'ADC';
    case AE = 'AE';
    case AG = 'AG';
    case AH = 'AH';
    case AI = 'AI';
    case AL = 'AL';
    case ALZ = 'ALZ';
    case AM = 'AM';
    case AMU = 'AMU';
    case AN = 'AN';
    case AO = 'AO';
    case AQ = 'AQ';
    case AQS = 'AQS';
    case AR = 'AR';
    case AT = 'AT';
    case AU = 'AU';
    case AV = 'AV';
    case AW = 'AW';
    case AX = 'AX';
    case BC = 'BC';
    case BF = 'BF';
    case BH = 'BH';
    case BN = 'BN';
    case BS = 'BS';
    case BU = 'BU';
    case BW = 'BW';
    case BX = 'BX';
    case CA = 'CA';
    case CAC = 'CAC';
    case CAF = 'CAF';
    case CAH = 'CAH';
    case CAM = 'CAM';
    case CAN = 'CAN';
    case CAV = 'CAV';
    case CAW = 'CAW';
    case CAX = 'CAX';
    case CE = 'CE';
    case CEU = 'CEU';
    case CEV = 'CEV';
    case CF = 'CF';
    case CFA = 'CFA';
    case CFD = 'CFD';
    case CFU = 'CFU';
    case CG = 'CG';
    case CGG = 'CGG';
    case CH = 'CH';
    case CI = 'CI';
    case CIF = 'CIF';
    case CJ = 'CJ';
    case CK = 'CK';
    case CL = 'CL';
    case CLA = 'CLA';
    case CLAM = 'CLAM';
    case CLAS = 'CLAS';
    case CLPD = 'CLPD';
    case CLTA = 'CLTA';
    case CLW = 'CLW';
    case CM = 'CM';
    case CN = 'CN';
    case CNK = 'CNK';
    case CNN = 'CNN';
    case CNR = 'CNR';
    case CNU = 'CNU';
    case CO = 'CO';
    case COS = 'COS';
    case COT = 'COT';
    case CP = 'CP';
    case CQ = 'CQ';
    case CR = 'CR';
    case CS = 'CS';
    case CSH = 'CSH';
    case CSI = 'CSI';
    case CST = 'CST';
    case CTG = 'CTG';
    case CU = 'CU';
    case CVNP = 'CVNP';
    case CX = 'CX';
    case CZ = 'CZ';
    case DD = 'DD';
    case DO = 'DO';
    case DS = 'DS';
    case DZ = 'DZ';
    case EAW = 'EAW';
    case EBE = 'EBE';
    case EDA = 'EDA';
    case EI = 'EI';
    case EL = 'EL';
    case ELE = 'ELE';
    case ER = 'ER';
    case ET = 'ET';
    case EU = 'EU';
    case EV = 'EV';
    case EXA = 'EXA';
    case EXC = 'EXC';
    case EXD = 'EXD';
    case EZ = 'EZ';
    case FFC = 'FFC';
    case FFCNA = 'FFCNA';
    case FG = 'FG';
    case FL = 'FL';
    case FLP = 'FLP';
    case FT = 'FT';
    case FU = 'FU';
    case FX = 'FX';
    case GF = 'GF';
    case GG = 'GG';
    case HD = 'HD';
    case HG = 'HG';
    case HH = 'HH';
    case HO = 'HO';
    case HR = 'HR';
    case HS = 'HS';
    case HSU = 'HSU';
    case IB = 'IB';
    case IF = 'IF';
    case IM = 'IM';
    case IMI = 'IMI';
    case IP = 'IP';
    case IR = 'IR';
    case IV = 'IV';
    case KA = 'KA';
    case KAN = 'KAN';
    case KG = 'KG';
    case KN = 'KN';
    case KS = 'KS';
    case KW = 'KW';
    case LA = 'LA';
    case LE = 'LE';
    case MAV = 'MAV';
    case NB = 'NB';
    case NBS = 'NBS';
    case NBU = 'NBU';
    case ND = 'ND';
    case NG = 'NG';
    case NH = 'NH';
    case NN = 'NN';
    case NR = 'NR';
    case NS = 'NS';
    case NZ = 'NZ';
    case OB = 'OB';
    case OC = 'OC';
    case OH = 'OH';
    case ON = 'ON';
    case OS = 'OS';
    case OT = 'OT';
    case OV = 'OV';
    case OW = 'OW';
    case OX = 'OX';
    case PB = 'PB';
    case PD = 'PD';
    case PF = 'PF';
    case PL = 'PL';
    case R23 = 'R23';
    case RA = 'RA';
    case RE = 'RE';
    case RED = 'RED';
    case RN = 'RN';
    case RP = 'RP';
    case RS = 'RS';
    case RT = 'RT';
    case RU = 'RU';
    case RV = 'RV';
    case SA = 'SA';
    case SB = 'SB';
    case SE = 'SE';
    case SF = 'SF';
    case SH = 'SH';
    case SIU = 'SIU';
    case SN = 'SN';
    case SV = 'SV';
    case SW = 'SW';
    case SZD = 'SZD';
    case TA = 'TA';
    case TD = 'TD';
    case TE = 'TE';
    case TG = 'TG';
    case TR = 'TR';
    case TRC = 'TRC';
    case TRD = 'TRD';
    case TV = 'TV';
    case UB = 'UB';
    case UFR = 'UFR';
    case UML = 'UML';
    case UPB = 'UPB';
    case UR = 'UR';
    case US = 'US';
    case UT = 'UT';
    case VB = 'VB';
    case VE = 'VE';
    case VT = 'VT';
    case VU = 'VU';
    case WC = 'WC';
    case WD = 'WD';
    case WL = 'WL';
    case WZ = 'WZ';
    case XA = 'XA';
    case XAV = 'XAV';
    case XEU = 'XEU';
    case XFA = 'XFA';
    case XNB = 'XNB';
    case XX = 'XX';
    case ZA = 'ZA';
    case ZAW = 'ZAW';
    case ZB = 'ZB';
    case ZE = 'ZE';
    case ZK = 'ZK';
    case ZM = 'ZM';
    case ZN = 'ZN';
    case ZO = 'ZO';
    case ZP = 'ZP';
    case ZPB = 'ZPB';
    case ZS = 'ZS';
    case ZTE = 'ZTE';
    case ZU = 'ZU';
    case ZV = 'ZV';
    case ZVE = 'ZVE';
    case ZW = 'ZW';
    case ZY = 'ZY';

    public function description(): string
    {
        // @todo: make translatable
        return match($this) {
            self::AA => 'Abholauftrag eingegangen', // Pick up order received
            self::AAO, self::AAQ => 'Sendungsannahme durchgeführt', // Item accepted
            self::AB, self::ET, self::SN => 'Unvorhergesehenes Zustellhindernis', // Item could not be delivered
            self::AC => 'Annahme verweigert - Lieferung zu spät', // Item refused, delivery not in time
            self::ADC => 'Adressnacherfassung', // Address subsequent entry
            self::AE => 'Abholauftrag durchgeführt', // Item picked up
            self::AG => 'Abholauftrag storniert', // Pickup order cancelled
            self::AH => 'Annahme verweigert - beschädigt', // Item not accepted - damaged
            self::AI => 'Sendungsannahme im Ausland', // Item accepted abroad
            self::AL, self::ALZ => 'Lagerausgang zur Zollanmeldung/Bearbeitung', // Item leaving warehouse for customs declaration/processing
            self::AM => 'Annahme verweigert - Teillieferung', // Item refused because of incomplete shipment
            self::AMU => 'Sendung am Flughafen übergeben', // Item handed over at the airport
            self::AN => 'Annahme verweigert - Nachnahme falsch', // Item refused, COD amount incorrect
            self::AO => 'Sendungsannahme durchgeführt', // Item accepted
            self::AQ, self::AR => 'Retour - Annahme verweigert', // Item refused by consignee - return
            self::AQS => 'Sendungsannahme durchgeführt', // Item accepted
            self::AT, self::ON, self::OT, self::ZO => 'Sendung in Zustellung', // Item is out for delivery
            self::AU => 'Retour - Empfängeradresse ungenügend', // Item returned to sender - address incomplete
            self::AV => 'Annahme verweigert', // Item refused
            self::AW => 'Annahme verweigert - Ansprechpartner fehlt', // Item refused, contact person missing
            self::AX => 'Annahme verweigert - nicht bestellt', // Item refused, shipment not ordered
            self::BC => 'Anschriftsproblem', // Address incorrect / incomplete
            self::BF => 'Verzögerung - Schadensprotokoll erstellt', // Delay - damage report compiled
            self::BH, self::BN => 'Empfänger nicht angetroffen - benachrichtigt', // Consignee not available at time of delivery - carded
            self::BS => 'Verzögerung wegen Beschädigung - Inhaltsprüfung', // Delay due to damage - content checked
            self::BU, self::DD, self::DS, self::DZ, self::EZ, self::IV, self::NBU, self::SW, self::VE, self::VT, self::WC, self::WZ, self::XX => 'Sendung in Verteilung', // Item distributed
            self::BW => 'Nachnahmebetrag intern abgerechnet', // COD amount cleared internally
            self::BX => 'Nachnahmebetrag zur Überweisung verarbeitet', // COD amount processed for transfer
            self::CA => 'Sendung im Zollanmeldungsprozess', // Item in customs declaration process
            self::CAC, self::CAH, self::CAM, self::CAN, self::CAV, self::CAW, self::CAX, self::CEU, self::CEV, self::CFA, self::CFU, self::CGG, self::CIF, self::CNK, self::CNN, self::CNR, self::CNU, self::COS, self::CSH, self::CST, self::CTG, self::ZVE => 'Sendung in Klärung', // Clarification
            self::CAF => 'Zur Klärung an Post-Geschäftsstelle', // Clarification at postal service point
            self::CE => 'Verzögerung der Zollanmeldung - fehlende/magelhafte Zollerklärung', // Customs declaration delay - missing/inappropriate customs declaration
            self::CF => 'Sendung zollfrei abgefertigt', // Item has been cleared customs-free
            self::CFD => 'Dem Zoll zur Selbstverzollung übergeben', // Item handed over to customs authority for final delivery
            self::CG => 'Verzögerung bei Zollstellung wegen mangelnder Einfuhrinformation', // Additional information for customs required
            self::CH => 'Verzögerung bei Zollstellung wegen fehlender Zolldokumente', // Additional documents for customs required
            self::CI => 'Verzögerung der Zollanmeldung - fehlender Wertnachweis', // Customs declaration delay - missing proof of value
            self::CJ => 'Verzögerung wegen verbotenem Inhalt', // Delay due to banned content
            self::CK => 'Verzögerung bei Zollstellung wegen mangelhafter Rechnung', // Delay due to incomplete invoice
            self::CL => 'Verzögerung der Zollanmeldung - fehlende Importlizenz', // Customs declaration delay - missing import licence
            self::CLA => 'Verzögerung der Zollanmeldung - fehlende Einfuhrbewilligung Außenhandelsgesetz', // Customs declaration delay - missing import licence according to Foreign Trade Act
            self::CLAM, self::CLAS, self::CLTA, self::CLW => 'Verzögerung der Zollanmeldung - fehlende Einfuhrgenehmigung', // Customs declaration delay - missing import licence
            self::CLPD => 'Verzögerung der Zollanmeldung - fehlende Bestätigung betreffend Einfuhrprivilegien', // Customs declaration delay - missing confirmation concerning import privileges
            self::CM => 'Verzögerung bei Zollstellung wegen Einfuhrverbot im Bestimmungsland', // Delay due to import ban in country of destination
            self::CN => 'Verzögerung bei Zollstellung wegen fehlender UID/Importnummer', // Delay due to missing VAT number
            self::CO => 'Verzögerung bei Zollstellung wegen fehlendem Ursprungszertifikat', // Delay due to missing certificate of origin
            self::COT => 'Verzögerung der Zollanmeldung', // Customs declaration delay
            self::CP => 'Verzögerung bei Zollstellung wegen mangelhaftem Urspungszertifikat', // Delay due to incorrect certificate of origin
            self::CQ => 'Sendung vom Zoll ohne Angabe von Gründen zurückgehalten', // Retained by customs for unspecified reason
            self::CR => 'Zollanmeldung abgeschlossen', // Customs declaration completed
            self::CS => 'Einfuhrverbot-Absender verständigt', // Importation restricted - item not delivered
            self::CSI => 'Verzögerung der Zollanmeldung - Sendung unvollständig', // Customs declaration delay - incomplete shipment
            self::CU => 'Verzögerung der Zollanmeldung - fehlendes Rücksendezertifikat', // Customs declaration delay - missing return certificate
            self::CVNP => 'Verzögerung der Zollanmeldung - unplausibler Warenwert', // Customs declaration delay - implausible value of goods
            self::CX => 'Retour - Zollabfertigung nicht möglich', // Customs clearance impossible - return
            self::CZ => 'Verzögerung bei Zollstellung wegen fehlender Zollerklärung', // Delay due to missing  customs declaration
            self::DO => 'Sendung in Wunsch-Postfiliale eingelangt', // Item arrived at desired postal service point
            self::EAW => 'Sendung in Abholstation eingelangt', // Item arrived at Pick-Up Station
            self::EBE => 'e-Benachrichtigung versendet', // e-Notification sent
            self::EDA, self::EXD => 'Verzögerung – Sendung in Klärung', // Delay - Clarification
            self::EI => 'Sendung in Post-Geschäftsstelle eingelangt', // Item arrived at postal service point
            self::EL, self::ELE => 'Lagereingang - Zollanmeldungshindernis', // Item in warehouse - obstacle to customs declaration
            self::ER, self::EV, self::RS, self::NBS, self::RE, self::RED => 'Retour - Sendung konnte nicht zugestellt werden', // Item could not be delivered - return
            self::EU => 'Empfänger unbekannt/verzogen', // Consignee unknown/has moved
            self::EXA => 'Sendung bei Zoll-/ Sicherheitskontrolle', // Item presented to customs/security
            self::EXC => 'Sendung nach Zoll-/ Sicherheitskontrolle freigegeben', // Item passed customs-/security check
            self::FFC => 'Zollanmeldungshindernis - Rückmeldung vom Empfänger eingelangt', // Obstacle to customs declaration - Feedback received from consignee
            self::FFCNA => 'Zollanmeldungshindernis - Rückmeldung vom Empfänger mit Annahmeverweigerung', // Obstacle to customs declaration - Feedback from the consignee with refusal of acceptance
            self::FG => 'Firma (vorübergehend) geschlossen', // Company (temporarily) closed
            self::FL => 'Verzögerung wegen Fehlverteilung', // Item misrouted
            self::FLP => 'Verzögerung wegen Fehlleitung von unserem Partner', // Item misrouted form our Partner
            self::FT => 'Verzögerung wegen lokalem Feiertag', // Delivery delayed due to local holiday
            self::FU => 'Empfänger im Urlaub', // Consignee on vacation
            self::FX => 'Elektronische Ankündigung fehlerhaft (Adressfehler)', // Pre notification incorrect (address error)
            self::GF, self::GG, self::IF => 'Verzögerung durch mangelhafte Angaben/Papiere', // Delay due to missing documents
            self::HD => 'Sendung im Depot abholbereit', // Item ready for pick up at depot
            self::HG, self::OS, self::OV, self::OW, self::OX => 'Verzögerung - unvorhersehbares Zustellhindernis', // Delay due to force majeure
            self::HH, self::ZA, self::ZS, self::ZU, self::ZW, self::ZY => 'Sendung zugestellt', // Item delivered
            self::HO => 'Sendung in Post-Geschäftsstelle abholbereit', // Item ready for pick up at postal service point
            self::HR => 'Retour - unvorhersehbares Zustellhindernis', // Undeliverable due to force majeure - return
            self::HS, self::OH => 'Sendung zur Selbstabholung hinterlegt', // Item ready for pick up
            self::HSU => 'Annahme im Hermes Shop', // Item at Hermes Shop
            self::IB => 'Sendung im Bestimmungsland eingetroffen', // Item arrived in country of destination
            self::IM => 'Sendung in Österreich eingetroffen', // Item arrived in Austria
            self::IMI, self::SE => 'Elektronische Auftragsdaten wurden vom Versender übermittelt', // The sender has provided electronic shipment information
            self::IP => 'Einfuhrverbot im Bestimmungsland', // Import ban in country of destination
            self::IR => 'Retour - Einfuhrverbot', // Import ban - return
            self::KA, self::KN, self::KS, self::KW, self::PF => 'Abholhindernis', // Item not picked up
            self::KAN => 'Keine Annahme aufgrund Beschädigung', // Item not accepted - damaged
            self::KG, self::SH, self::TG => 'Verzögerung wegen Zustellhindernis', // Item could not be delivered
            self::LA => 'Sendungsannahme durch Zusteller', // Item accepted
            self::LE => 'Sendung im Postlager eingelangt', // Item at depot
            self::MAV => 'Mangelhafte Verpackung ausgebessert', // Insufficient packaging repaired
            self::NB, self::OB => 'Sendung noch nicht abgeholt', // Item not picked up
            self::ND => 'Zweiter Zustellversuch erfolglos', // 2nd delivery attempt unsuccessful
            self::NG, self::NH => 'Sendung wird nachgesendet', // Item redirected
            self::NN => 'Nachnahmebetrag unklar', // COD amount missing
            self::NR => 'Verzögerung durch fehlende Nachnahmedaten', // Delay due to missing COD data
            self::NS => 'Verzögerung - nicht systemkonform', // Delay due to incorrect information
            self::NZ, self::OC => 'Sendung wird nochmals zugestellt', // Item will be delivered again
            self::PB => 'e-Benachrichtigung versendet (Erinnerung)', // Pre notification sent (reminder)
            self::PD => 'Zweite Benachrichtigung zugestellt', // Second pre notification delivered
            self::PL => 'Sendung an das Postlager weitergeleitet', // Item forwarded to depot
            self::R23 => 'Sendung am Zielflughafen angekommen', // Item arrived at destination airport
            self::RA => 'Sendung in Abholstation eingelegt', // Item accepted at Pick-Up Station
            self::RN => 'Retour - Sendung nicht behoben', // Item not picked up - return
            self::RP => 'Retour - Postfach existiert nicht', // P.O. box does not exist - return
            self::RT, self::UR, self::UT => 'Übergabe an Kooperationspartner', // Item handed over to subcontractor
            self::RU, self::RV => 'Retour - Empfänger unbekannt/verzogen', // Consignee unknown - return
            self::SA => 'Sendung dem Empfänger übergeben/zum weiteren Transport an den Empfänger übergeben', // Item delivered to consignee/handed over for transport to the consignee
            self::SB => 'Retour - Sendung beschädigt', // Item damaged - return
            self::SF => 'Zustellhindernis – nochmaliger Zustellversuch', // Item could not be delivered – further delivery attempt
            self::SIU => 'Sendung ist unterwegs', // Item dispatched
            self::SV => 'Sendung dem Empfänger übergeben/zum weiteren Transport an den Empfänger übergeben', // Item delivered to consignee/handed over for transport to the consignee
            self::SZD => 'Sendung zugestellt (Digitalisierung)', // Item delivered (digitalization)
            self::TA, self::TE, self::TR => 'Transit', // Transit
            self::TD => 'Transitsendung – Beschädigung festgestellt', // Transit unit damaged
            self::TRC => 'Konsolidierung für Export', // Transit unit consolidation
            self::TRD => 'Auflösung einer konsolidierten Sendung', // Transit unit deconsolidation
            self::TV => 'Zustellung nach Terminvereinbarung', // Item will be delivered on appointment
            self::UB, self::US => 'Übergabe an Zustellpartner', // Item handed over to delivery partner
            self::UFR => 'Unterfrankierung Paketmarke', // Insufficient postage parcel stamp
            self::UML => 'Sendung wurde umgeleitet', // Item redirected
            self::UPB => 'Sendung in Post-Empfangsbox eingelangt', // Item arrived at Post Pick-Up Box
            self::VB => 'Sendung in Versandbox/-station eingelegt', // Item accepted at sendbox
            self::VU => 'Sendung zugestellt - Vertrag unterschrieben', // Item delivered - contract signed
            self::WD => 'Elektronische Ankündigung fehlerhaft', // Pre notification incorrect
            self::WL => 'Sendung wurde weitergeleitet', // Item forwarded
            self::XA => 'Sendung ins Zielland weitergeleitet', // Item forwarded to destination country
            self::XAV => 'Annahme verweigert', // Item refused
            self::XEU => 'Empfänger unbekannt/verzogen', // Consignee unknown/has moved
            self::XFA => 'Empfängeradresse ungenügend', // Consignee address incomplete
            self::XNB => 'Keine Rückmeldung vom Empfänger', // No response from consignee
            self::ZAW => 'Sendung von Abholstation abgeholt', // Item picked up at Pick-Up Station
            self::ZB => 'Sendung an Übernahmsberechtigten übergeben', // Item delivered to authorized representative
            self::ZE => 'Sendung an Ersatzabgabestelle zugestellt', // Item delivered to alternative address
            self::ZK => 'Sendung an Angestellten/Kollegen übergeben', // Item delivered to employee/colleague
            self::ZM => 'Sendung an Mitbewohner/in zugestellt', // Item delivered to flat mate
            self::ZN => 'Sendung an Nachbarn/in zugestellt', // Item delivered to neighbor
            self::ZP => 'Sendung an Empfänger übergeben', // Item delivered to consignee
            self::ZPB => 'Sendung von Post-Empfangsbox abgeholt', // Post Pick-Up Box - Item picked up
            self::ZTE => 'Zum Transport erhalten', // Item accepted
            self::ZV => 'Sendung an Postbevollmächtigten übergeben', // Item delivered to authorized representative
        };
    }
}
